spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:roommind_dev_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
